# Numpy

In [1]:
import numpy as np

Numpy es una librería que trabaja con grandes conjuntos de datos numéricos de forma eficiente, realiza complejas operaciones matemáticas y estadísticas de alto rendimiento.

El elemento principal de esta librería son los arrays, éstos pueden representarse en distintas dimensiones.

## 1.1 Dimensiones

Las dimensiones nos permiten estructurar los datos de tal forma que sea posible abordar problemas complejos con más eficiencia y precisión.

Podemos encontrar las dimensiones como:
- 0 dimensiones = Escalar
- 1 dimensión = Vector
- 2 dimensiones = Matriz
- +3 dimensiones = Tensor

Cada una de las dimensiones tiene un proposito especifico.

**Escalar**: Se utiliza para mediciones individuales, pues un escalar es en si un simple valor numérico.

In [16]:
escalar = np.array(36)
print(f"{escalar}, type: {escalar.dtype}, dimensión: {escalar.ndim}")

36, type: int64, dimensión: 0


**Vector**: Colección de más de un escalar, se utilizan cuando los datos pueden organizarse como una fila o una columna, como las características una sola observación (edad, altura, peso, etc.)

In [13]:
vector = np.array([36, 32, 29, 30, 30, 31, 33])
print(f"{vector},\ntype: {vector.dtype}, dimensión: {vector.ndim}")

[36 32 29 30 30 31 33],
type: int64, dimensión: 1


**Matriz**: Organiza la información a modo de filas y columnas, es utilizada cuando se cuenta con una estructura bidimensional. Ejemplo, (1) Dataset donde las filas representan las observaciones y las columnas las características. (2) O bien una imagen en escala de grices, donde cada celta (fila-columna) representa un pixel.

In [14]:
matrix = np.array([[1,2,3], [4,5,6]])
print(f"{matrix},\ntype: {matrix.dtype}, dimensión: {matrix.ndim}")

[[1 2 3]
 [4 5 6]],
type: int64, dimensión: 2


**Tensor**: Los datos tienen 3 o más dimensiones, un ejemplo de un tensor 3D es una (1) imagen a color, ccada dimensión representa algo diferente: alto, ancho y canales de color (RGB). (2) O bien podemos encontrar que un tensor 4D representa un video, donde encontramos una dimensión para el núnero de frames, alto, ancho y canales de color.

In [15]:
tensor = tensor = np.array([
  [[1,2], [3,4], [5,6]],
  [[7,8], [9,10], [11,12]],
  [[13,14], [15,16], [17,18]]
])
print(f"{tensor},\ntype: {tensor.dtype}, dimensión: {tensor.ndim}")

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]],
type: int64, dimensión: 3


Numpy nos ofrece 6 mecanismos distintos para crear arrays:
1. **Conversión**: Desde otras estructuras de pyhon (listas y tuplas).
2. **Funciones**: Ya vienen por defecto en Numpy (arange, ones, zeros, eye, etc.).
3. **Replicación**: Unión o mutación de vectores o matrices existentes.
4. **Lectura desde disco**: Leer archivos de texto, csv o formatos personalizados.
5. **Bytes crudos**: Por medio de cadenas o Buffers.
6. **Funciones especiales**: Provenientes de librerías externas (random)

In [20]:
array = np.arange(0,5)
print(array)
array + 5

[0 1 2 3 4]


array([5, 6, 7, 8, 9])