# Numpy

In [2]:
import numpy as np

Numpy es una librería que trabaja con grandes conjuntos de datos numéricos de forma eficiente, realiza complejas operaciones matemáticas y estadísticas de alto rendimiento.

El elemento principal de esta librería son los arrays, éstos pueden representarse en distintas dimensiones.

## 1.1 Dimensiones

Las dimensiones nos permiten estructurar los datos de tal forma que sea posible abordar problemas complejos con más eficiencia y precisión.

Podemos encontrar las dimensiones como:
- 0 dimensiones = Escalar
- 1 dimensión = Vector
- 2 dimensiones = Matriz
- +3 dimensiones = Tensor

Cada una de las dimensiones tiene un proposito especifico.

**Escalar**: Se utiliza para mediciones individuales, pues un escalar es en si un simple valor numérico.

In [3]:
escalar = np.array(36)
print(f"{escalar}, type: {escalar.dtype}, dimensión: {escalar.ndim}")

36, type: int64, dimensión: 0


**Vector**: Colección de más de un escalar, se utilizan cuando los datos pueden organizarse como una fila o una columna, como las características una sola observación (edad, altura, peso, etc.)

In [4]:
vector = np.array([36, 32, 29, 30, 30, 31, 33])
print(f"{vector},\ntype: {vector.dtype}, dimensión: {vector.ndim}")

[36 32 29 30 30 31 33],
type: int64, dimensión: 1


**Matriz**: Organiza la información a modo de filas y columnas, es utilizada cuando se cuenta con una estructura bidimensional. Ejemplo, (1) Dataset donde las filas representan las observaciones y las columnas las características. (2) O bien una imagen en escala de grices, donde cada celta (fila-columna) representa un pixel.

In [5]:
matrix = np.array([[1,2,3], [4,5,6]])
print(f"{matrix},\ntype: {matrix.dtype}, dimensión: {matrix.ndim}")

[[1 2 3]
 [4 5 6]],
type: int64, dimensión: 2


**Tensor**: Los datos tienen 3 o más dimensiones, un ejemplo de un tensor 3D es una (1) imagen a color, ccada dimensión representa algo diferente: alto, ancho y canales de color (RGB). (2) O bien podemos encontrar que un tensor 4D representa un video, donde encontramos una dimensión para el núnero de frames, alto, ancho y canales de color.

In [6]:
tensor = tensor = np.array([
  [[1,2], [3,4], [5,6]],
  [[7,8], [9,10], [11,12]],
  [[13,14], [15,16], [17,18]]
])
print(f"{tensor},\ntype: {tensor.dtype}, dimensión: {tensor.ndim}")

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]],
type: int64, dimensión: 3


Numpy nos ofrece 6 mecanismos distintos para crear arrays:
1. **Conversión**: Desde otras estructuras de pyhon (listas y tuplas).
2. **Funciones**: Ya vienen por defecto en Numpy (arange, ones, zeros, eye, etc.).
3. **Replicación**: Unión o mutación de vectores o matrices existentes.
4. **Lectura desde disco**: Leer archivos de texto, csv o formatos personalizados.
5. **Bytes crudos**: Por medio de cadenas o Buffers.
6. **Funciones especiales**: Provenientes de librerías externas (random)

In [7]:
array = np.arange(0,5)
print(array)
array + 5

[0 1 2 3 4]


array([5, 6, 7, 8, 9])

## 1.2 Arrays

Específicamente en Numpy, un array es una estructura de datos homogénea organizada en una o más dimensiones. Esencial para cálculos matemáticos de manera eficiente y rápida.

En el análisis y procesamiento de datos, los arrays de Numpy son superiores a las listas de Python, ya que la librería ofrece funciones matemáticas y estadísticas  avanzadas ya optimizadas para estas estructura. 

📌 `array > lista`

Con esta herramienta se uede representar:
- Imágenes
- Sonidos
- Videos
- Textos
- etc...

### 1.2.1 Formas de crear arrays con `numpy`

**Funciones a partir de una forma predefinida** <br>
Este tipo de funciones tienen en comun los parametros `shape` que define la forma del array, y `dtype` para indicar el tipo de dato que contendra el array.

- `empty()`: Crea un array con valores arbitrarios, "vacío" o sin inicializar. Lo cuál significa que su contenido no se establece en 0 o en cualquier otro valor predefinido
- `eye()`: Crea un array bidimensional (2D) compuesta por 0 y 1, los elementos de la diagonal principal tienen el valor de 1, en otras palabras crea una matriz identidad.
- `identity()`: Crea una matriz identidad cuadrada (`nxn`), similar a eye pero con una sintaxis más sencilla

In [10]:
# Array de 2 dimensiones (matriz)
print("*"*5, "empty()", "*"*5)
empy_array_2d = np.empty(shape=(4,4), dtype="uint8")
print(empy_array_2d)
print(f"Forma: {empy_array_2d.shape}, dimensión: {empy_array_2d.ndim}, tipo: {empy_array_2d.dtype}\n")


print("*"*5, "eye()", "*"*5)
eye_matrix__1 = np.eye(N=4, k=-1)
print(f"Matriz identidad con la diagonal principal en la parte inferior")
print(eye_matrix__1)
print(f"Forma: {eye_matrix__1.shape}, dimensión: {eye_matrix__1.ndim}, tipo: {eye_matrix__1.dtype}\n")

print("*"*5, "identity()", "*"*5)
identity_array_v1 = np.identity(n=3)
print(identity_array_v1)
print(f"Forma: {identity_array_v1.shape}, dimensión: {identity_array_v1.ndim}, tipo: {identity_array_v1.dtype}\n")\


***** empty() *****
[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
Forma: (4, 4), dimensión: 2, tipo: uint8

***** eye() *****
Matriz identidad con la diagonal principal en la parte inferior
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
Forma: (4, 4), dimensión: 2, tipo: float64

***** identity() *****
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Forma: (3, 3), dimensión: 2, tipo: float64



- `ones()`: Esta función crea un array de una determinada forma, cada elemento se inicializa con el valor de 1.
- `zeros()`: Esta función crea un array de una determinada forma, cada elemento se inicializa con el valor de 0.
- `full()`: Crea un array con de una determinada forma, cada elemento esta inicializado con el valor especificado al crear el array.

In [11]:

print("*"*5, "ones()", "*"*5)
ones_v1 = np.ones(shape=(5, 5), dtype="int32")
print(ones_v1)
print(f"Forma: {ones_v1.shape}, dimensión: {ones_v1.ndim}, tipo: {ones_v1.dtype}\n")

print("*"*5, "zeros()", "*"*5)
zeros_v1 = np.zeros(shape=3)
print(zeros_v1)
print(f"Forma: {zeros_v1.shape}, dimensión: {zeros_v1.ndim}, tipo: {zeros_v1.dtype}\n")

print("*"*5, "full()", "*"*5)
fill_array = np.full(shape=(3,3), fill_value=[5.5, 0, 3])
print(fill_array)
print(f"Forma: {fill_array.shape}, dimensión: {fill_array.ndim}, tipo: {fill_array.dtype}\n")

***** ones() *****
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Forma: (5, 5), dimensión: 2, tipo: int32

***** zeros() *****
[0. 0. 0.]
Forma: (3,), dimensión: 1, tipo: float64

***** full() *****
[[5.5 0.  3. ]
 [5.5 0.  3. ]
 [5.5 0.  3. ]]
Forma: (3, 3), dimensión: 2, tipo: float64



Cada método tiene una funcionalidad y objetivo especifico, según las necesidades del proyecto que estemos realizando.
En este [notebook de google colab](https://colab.research.google.com/drive/1ORRBfv7sDnOPh2tzomCSzVpZZV-0XH-_#scrollTo=vTHWAn3jR3HK) hay más ejemplos de creación de arrays con otras funciones ya integradas de numpy.

## 1.3 Indexación y Slicing

**Indexación** <br>
Forma de acceder a los elementos de un array por medio de su índice.<br>
📢 Los indices empiezan a partir del 0 que representa el primer elemento del array.

In [31]:
array = np.random.randint(5, 30, 20) 
print(array)

[29 22 22 23 17 19 27 26 25 17  8 21 16 19 15 28 19 11 27 17]


In [32]:
print("Elemento en la posición 5:", array[4])
print("Elemento en la primer posición:", array[0])
print("Elemento en la última posición", array[-1])
print("Elemento en la ante última posición", array[-2])

Elemento en la posición 5: 17
Elemento en la primer posición: 29
Elemento en la última posición 17
Elemento en la ante última posición 27


**Indexación booleana** <br>
Forma de obtener datos a partir de una condición. <br>
📢 Todos los elementos que cumplan con la condición serán “devueltos”.

In [33]:
bool_index = array > 15
print("Array booleano:", bool_index)
print("Elementos mayortes a 15:", array[bool_index])
print("Elementos entre 15 y 20:", array[(array >= 15 ) & (array <= 20)])

Array booleano: [ True  True  True  True  True  True  True  True  True  True False  True
  True  True False  True  True False  True  True]
Elementos mayortes a 15: [29 22 22 23 17 19 27 26 25 17 21 16 19 28 19 27 17]
Elementos entre 15 y 20: [17 19 17 16 19 15 19 17]


**Indexación por listas** <br>
Permite obtener multiples elementos de un array con una lista de indices. <br>
📢 Al mandarle indices “desordenados” el array resultante obtiene los elementos en el orden en que se pasó el índice centro de la lista.

In [34]:
index_list = [3,8,5,0]
print("Elementos en las posiciones 3,8,5 y 0:", array[index_list])
print("Elementos en las posiciones -1, 2,3 y 5:", array[[-1,2,3, 5]])

Elementos en las posiciones 3,8,5 y 0: [23 25 19 29]
Elementos en las posiciones -1, 2,3 y 5: [17 22 23 19]


**Indexación de arrays multidimensionales** >br
Para acceder a un elemento de un array bidimensional, le indicamos 2 indices. <br>
📢 [indice_fila, indice_columna]

In [35]:
matrix = np.random.randint(5, 30, (5,5))
matrix

array([[15,  5, 23, 26, 15],
       [ 8, 11, 18, 11, 14],
       [28, 25,  7, 22, 14],
       [18, 25, 27, 24, 24],
       [ 5, 13, 20, 29, 29]])

In [40]:
print("Elemento de la fila 2, columna 2:", matrix[2,2]) # Elemento especifio
print("Elementos de las fila 1 y 2, columna 2:", matrix[[1,2],2]) # Indexaciónb por lista (1)
print("Elementos en la fila 1 , columna 2, y fila 3, columna 2:", matrix[[1,2],[3,2]]) # Indexaciónb por lista (2)
print("Elementos mayores a 18:", matrix[matrix > 18]) # Indexación booleana

Elemento de la fila 2, columna 2: 7
Elementos de las fila 1 y 2, columna 2: [18  7]
Elementos en la fila 1 , columna 2, y fila 3, columna 2: [11  7]
Elementos mayores a 18: [23 26 28 25 22 25 27 24 24 20 29 29]


**Slicing** <br>
Selección de sub-arrays, donde le indicamos el índice inicial e índice final del conjunto original. <br>
📢 También se se pueden agregar “saltos”.

In [64]:
print("*"*5, "Array", "*"*5)
print("Elementos desde el incio hasta la posición 3:", array[:3])
print("Elementos desde la posición 5 hasta el final:", array[5:])
print("Elementos desde la posición 5 hasta la posición 10:", array[5:10])
print("Elementos desde la posición hasta la penultima posición dando 2 saltos:", array[3:-2:2])

***** Array *****
Elementos desde el incio hasta la posición 3: [29 22 22]
Elementos desde la posición 5 hasta el final: [19 27 26 25 17  8 21 16 19 15 28 19 11 27 17]
Elementos desde la posición 5 hasta la posición 10: [19 27 26 25 17]
Elementos desde la posición hasta la penultima posición dando 2 saltos: [23 19 26 17 21 19 28 11] 

***** Matriz *****
Elementos a partir de la fila uno, y columnas a partir de la fila 2 [[18 11 14]
 [ 7 22 14]
 [27 24 24]
 [20 29 29]]





In [69]:
print("*"*5, "Matriz", "*"*5)
print("Elementos a partir de la fila uno, y columnas a partir de la fila 2:\n", matrix[1:, 2:])
print("Elementos hasta la fila 3, y hasta la columna 2:\n", matrix[:3, :2])
print("Elementos a partir de la fila 1 dando 2 saltos, hasta la columna 1 dando 2 saltos\n",matrix[1::2, :1:2])

***** Matriz *****
Elementos a partir de la fila uno, y columnas a partir de la fila 2:
 [[18 11 14]
 [ 7 22 14]
 [27 24 24]
 [20 29 29]]
Elementos hasta la fila 3, y hasta la columna 2:
 [[15  5]
 [ 8 11]
 [28 25]]
Elementos a partir de la fila 1 dando 2 saltos, hasta la columna 1 dando 2 saltos
 [[ 8]
 [18]]
